# Generated by Django 3.2.25 on 2025-03-15 17:49

from django.db import migrations, models

import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=events.utils.get_year, verbose_name="Årgang"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="response_deadline",
            field=models.DateTimeField(verbose_name="Response deadline"),
        ),
    ]
