# Generated by Django 3.2.25 on 2025-03-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_auto_20241230_2158"),
        ("events", "0002_auto_20250315_1849"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="album",
                to="gallery.album",
                verbose_name="Event album",
            ),
        ),
    ]
