# Generated by Django 2.2.2 on 2019-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20190611_0031"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"ordering": ("-start_datetime",)},
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="Ukendt", max_length=255),
            preserve_default=False,
        ),
    ]
