# Generated by Django 3.2.25 on 2025-03-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20250316_1050"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("name", "year")},
        ),
    ]
