# Generated by Django 2.2.2 on 2019-07-17 12:56

from django.db import migrations, models
import django.db.models.deletion


def set_event_for_event_choices(apps, schema_editor):
    EventChoice = apps.get_model('events', 'EventChoice')
    for event_choice in EventChoice.objects.all():
        events = event_choice.event_set.all()
        assert len(events) == 1
        event_choice.event = events[0]
        event_choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventchoiceoption_max_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchoice',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_choices', to='events.Event'),
            preserve_default=False,
        ),
        migrations.RunPython(set_event_for_event_choices),
        migrations.AlterField(
            model_name='eventchoice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_choices', to='events.Event'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_choices',
        ),
    ]
