# Generated by Django 3.2.25 on 2026-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, verbose_name="Link to additional information"
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
