# Generated by Django 2.2.2 on 2019-07-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190717_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventresponse',
            old_name='choices',
            new_name='selected_options',
        ),
    ]
