# Generated by Django 3.2.25 on 2026-02-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_commonevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonevent",
            options={"ordering": ("date",)},
        ),
    ]
