# Generated by Django 3.0.6 on 2020-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0040_auto_20200113_2022"),
        ("events", "0007_auto_20190814_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="bartender_blacklist",
            field=models.ManyToManyField(
                blank=True, related_name="blacklisted_events", to="bartenders.Bartender"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="bartender_whitelist",
            field=models.ManyToManyField(
                blank=True, related_name="whitelisted_events", to="bartenders.Bartender"
            ),
        ),
    ]
