# Generated by Django 6.0.4 on 2026-07-11 23:17

import django.db.models.deletion
from django.db import migrations, models

import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0020_lowercase_emails"),
        ("events", "0007_alter_commonevent_options"),
        ("gallery", "0007_alter_album_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("common", "Common Event"), ("internal", "Bartender event")],
                default="internal",
                help_text="Common events are visible to all bartenders, while bartender events are only visible to bartenders who are allowed to attend.",
                max_length=20,
                verbose_name="Event type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="bartender_blacklist",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bartenders who are not allowed to attend the event. If empty, all bartenders are allowed to attend.",
                related_name="blacklisted_events",
                to="bartenders.bartender",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="bartender_whitelist",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bartenders who are allowed to attend the event. If empty, all bartenders are allowed to attend.",
                related_name="whitelisted_events",
                to="bartenders.bartender",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the event.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_album",
            field=models.ForeignKey(
                blank=True,
                help_text="The album associated with the event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="gallery.album",
                verbose_name="Event album",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="The location of the event.",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                help_text="The visible name of the event.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="response_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="The deadline for bartenders to respond to the event invitation.",
                null=True,
                verbose_name="Response deadline",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=events.utils.get_year,
                help_text="The year of the event.",
                verbose_name="Årgang",
            ),
        ),
        migrations.AlterField(
            model_name="eventchoice",
            name="event",
            field=models.ForeignKey(
                help_text="The event this choice is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_choices",
                to="events.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventchoice",
            name="name",
            field=models.CharField(
                help_text="The visible name of the choice.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="eventchoiceoption",
            name="event_choice",
            field=models.ForeignKey(
                help_text="The event choice this option is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="events.eventchoice",
                verbose_name="Event choice",
            ),
        ),
        migrations.AlterField(
            model_name="eventchoiceoption",
            name="max_selected",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The maximum number of bartenders that can select this option. Leave blank for no limit.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventchoiceoption",
            name="option",
            field=models.CharField(
                help_text="The visible name of the option.",
                max_length=255,
                verbose_name="Option",
            ),
        ),
        migrations.AlterField(
            model_name="eventresponse",
            name="attending",
            field=models.BooleanField(
                help_text="Whether the bartender is attending the event."
            ),
        ),
        migrations.AlterField(
            model_name="eventresponse",
            name="bartender",
            field=models.ForeignKey(
                help_text="The bartender who submitted this response.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_responses",
                to="bartenders.bartender",
                verbose_name="Bartender",
            ),
        ),
        migrations.AlterField(
            model_name="eventresponse",
            name="event",
            field=models.ForeignKey(
                help_text="The event this response is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="events.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventresponse",
            name="selected_options",
            field=models.ManyToManyField(
                help_text="The options selected by the bartender for this event response.",
                related_name="event_responses",
                to="events.eventchoiceoption",
                verbose_name="Selected options",
            ),
        ),
        migrations.CreateModel(
            name="EventLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        default="facebook",
                        help_text="The type of link. This determines the default title and icon for the link.",
                        max_length=20,
                        verbose_name="Link type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Override the displayed title of the link. Leave blank to use the default title for the link type.",
                        max_length=25,
                        verbose_name="Title",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL of the link.", verbose_name="URL"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this link is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
        ),
    ]
