# Generated by Django 6.0.4 on 2026-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_event_type_alter_event_bartender_blacklist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="internal_description",
            field=models.TextField(
                blank=True,
                help_text="This will display for bartenders instead of the public description. Leave blank to use the public description. This is useful for internal information that should not be visible to the public. For example when the event is common but it has internal information for bartenders.",
                verbose_name="Internal description",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of the event. This will be visible to all users.",
                verbose_name="Public description",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
    ]
