# Generated by Django 6.0.4 on 2026-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_internal_description_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("common", "Common Event"), ("internal", "Bartender event")],
                default="internal",
                help_text="Common events are visible to everyone, while bartender events are only visible to bartenders.",
                max_length=20,
                verbose_name="Event type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="internal_description",
            field=models.TextField(
                blank=True,
                help_text="Internal information shown only to bartenders.",
                verbose_name="Internal description",
            ),
        ),
    ]
