# Generated by Django 6.0.4 on 2026-08-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_event_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommonEvent",
        ),
    ]
