# Generated by Django 3.2.25 on 2025-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UdlejningBoardGameCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateFrom", models.DateTimeField()),
                ("dateTo", models.DateTimeField()),
                ("whoReserved", models.TextField(blank=True, max_length=140)),
                ("contactInfo", models.CharField(blank=True, max_length=140)),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("dateFrom",),
            },
        ),
    ]
