# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udlejning',
            old_name='paymentSendTo',
            new_name='billSendTo',
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='whoPays',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='whoReserved',
            field=models.CharField(max_length=140),
        ),
    ]
