# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0002_auto_20170325_1618'),
        ('udlejning', '0002_auto_20170325_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='udlejning',
            name='bartendersInCharge',
            field=models.ManyToManyField(blank=True, to='bartenders.Bartender'),
        ),
        migrations.AddField(
            model_name='udlejninggrill',
            name='bartendersInCharge',
            field=models.ManyToManyField(blank=True, to='bartenders.Bartender'),
        ),
    ]
