# Generated by Django 3.2.25 on 2025-01-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0002_udlejningboardgamecart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="udlejning",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning",
                "verbose_name_plural": "Udlejninger",
            },
        ),
        migrations.AlterModelOptions(
            name="udlejningapplication",
            options={
                "ordering": ("created",),
                "verbose_name": "Udlejningsansøgning",
                "verbose_name_plural": "Udlejningsansøgninger",
            },
        ),
        migrations.AlterModelOptions(
            name="udlejningboardgamecart",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning af brætspilsvogn",
                "verbose_name_plural": "Udlejning af brætspilsvogn",
            },
        ),
        migrations.AlterModelOptions(
            name="udlejninggrill",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning af grill",
                "verbose_name_plural": "Udlejning af grill",
            },
        ),
        migrations.AlterModelOptions(
            name="udlejningprojector",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning af projektor",
                "verbose_name_plural": "Udlejning af projektor",
            },
        ),
        migrations.AlterModelOptions(
            name="udlejningspeakers",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning af højtaler",
                "verbose_name_plural": "Udlejning af højtalere",
            },
        ),
    ]
