# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-25 16:29
from __future__ import unicode_literals

from django.db import migrations


# Copies boardMember-bartender foreign key values for Udlejning and UdlejningGrill
def copy_foreign_keys(apps, schema_editor):
    for model_name in ('Udlejning', 'UdlejningGrill'):
        Model = apps.get_model('udlejning', model_name)
        for udlejning in Model.objects.exclude(boardMemberInCharge__isnull=True).select_related('boardMemberInCharge'):
            udlejning.bartendersInCharge.add(udlejning.boardMemberInCharge.bartender)  # Copy the fk


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0003_add_bartenderInCharge_fields'),
    ]

    operations = [
        migrations.RunPython(copy_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
