# Generated by Django 3.2.25 on 2025-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
        ("udlejning", "0003_auto_20250119_0844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="udlejning",
            name="billSendTo",
        ),
        migrations.AddField(
            model_name="udlejningboardgamecart",
            name="bartendersInCharge",
            field=models.ManyToManyField(
                to="bartenders.Bartender", verbose_name="Ansvarlige"
            ),
        ),
        migrations.AddField(
            model_name="udlejningboardgamecart",
            name="where",
            field=models.TextField(
                default=None, max_length=140, null=True, verbose_name="Lokation"
            ),
        ),
        migrations.AddField(
            model_name="udlejningprojector",
            name="bartendersInCharge",
            field=models.ManyToManyField(
                to="bartenders.Bartender", verbose_name="Ansvarlige"
            ),
        ),
        migrations.AddField(
            model_name="udlejningprojector",
            name="where",
            field=models.TextField(
                default=None, max_length=140, null=True, verbose_name="Lokation"
            ),
        ),
        migrations.AddField(
            model_name="udlejningspeakers",
            name="bartendersInCharge",
            field=models.ManyToManyField(
                to="bartenders.Bartender", verbose_name="Ansvarlige"
            ),
        ),
        migrations.AddField(
            model_name="udlejningspeakers",
            name="where",
            field=models.TextField(
                default=None, max_length=140, null=True, verbose_name="Lokation"
            ),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="bartendersInCharge",
            field=models.ManyToManyField(
                to="bartenders.Bartender", verbose_name="Ansvarlige"
            ),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="comments",
            field=models.TextField(
                blank=True, max_length=420, verbose_name="Kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="draftBeerSystem",
            field=models.CharField(
                choices=[("small", "Lille"), ("medium", "Mellem")],
                help_text="Hvilket anlæg vil I låne?",
                max_length=16,
                verbose_name="Fadølsanlæg",
            ),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="expectedConsummation",
            field=models.TextField(
                help_text="Hvilke slags øl eller andre drikkevarer ønskes der og hvor mange fustager af hver type?",
                max_length=280,
                verbose_name="Forventet forbrug",
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="comments",
            field=models.TextField(
                blank=True, max_length=420, verbose_name="Kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="expectedConsummation",
            field=models.TextField(
                help_text="Hvilke slags øl eller andre drikkevarer ønskes der og hvor mange fustager af hver type?",
                max_length=280,
                verbose_name="Forventet forbrug",
            ),
        ),
        migrations.AlterField(
            model_name="udlejningboardgamecart",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Kommentarer"),
        ),
        migrations.AlterField(
            model_name="udlejningboardgamecart",
            name="contactInfo",
            field=models.CharField(max_length=140, verbose_name="Kontakt info"),
        ),
        migrations.AlterField(
            model_name="udlejningboardgamecart",
            name="dateFrom",
            field=models.DateTimeField(verbose_name="Start dato & tid"),
        ),
        migrations.AlterField(
            model_name="udlejningboardgamecart",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Slut dato & tid"
            ),
        ),
        migrations.AlterField(
            model_name="udlejningboardgamecart",
            name="whoReserved",
            field=models.TextField(max_length=140, verbose_name="Hvem er I?"),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="bartendersInCharge",
            field=models.ManyToManyField(
                to="bartenders.Bartender", verbose_name="Ansvarlige"
            ),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Kommentarer"),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="contactInfo",
            field=models.CharField(max_length=140, verbose_name="Kontakt info"),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="dateFrom",
            field=models.DateTimeField(verbose_name="Start dato & tid"),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Slut dato & tid"
            ),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="where",
            field=models.TextField(
                default=None, max_length=140, null=True, verbose_name="Lokation"
            ),
        ),
        migrations.AlterField(
            model_name="udlejninggrill",
            name="whoReserved",
            field=models.TextField(max_length=140, verbose_name="Hvem er I?"),
        ),
        migrations.AlterField(
            model_name="udlejningprojector",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Kommentarer"),
        ),
        migrations.AlterField(
            model_name="udlejningprojector",
            name="contactInfo",
            field=models.CharField(max_length=140, verbose_name="Kontakt info"),
        ),
        migrations.AlterField(
            model_name="udlejningprojector",
            name="dateFrom",
            field=models.DateTimeField(verbose_name="Start dato & tid"),
        ),
        migrations.AlterField(
            model_name="udlejningprojector",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Slut dato & tid"
            ),
        ),
        migrations.AlterField(
            model_name="udlejningprojector",
            name="whoReserved",
            field=models.TextField(max_length=140, verbose_name="Hvem er I?"),
        ),
        migrations.AlterField(
            model_name="udlejningspeakers",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Kommentarer"),
        ),
        migrations.AlterField(
            model_name="udlejningspeakers",
            name="contactInfo",
            field=models.CharField(max_length=140, verbose_name="Kontakt info"),
        ),
        migrations.AlterField(
            model_name="udlejningspeakers",
            name="dateFrom",
            field=models.DateTimeField(verbose_name="Start dato & tid"),
        ),
        migrations.AlterField(
            model_name="udlejningspeakers",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Slut dato & tid"
            ),
        ),
        migrations.AlterField(
            model_name="udlejningspeakers",
            name="whoReserved",
            field=models.TextField(max_length=140, verbose_name="Hvem er I?"),
        ),
    ]
