# Generated by Django 3.2.25 on 2025-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
        ("udlejning", "0004_auto_20250605_2049"),
    ]

    operations = [
        migrations.CreateModel(
            name="UdlejningTent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateFrom", models.DateTimeField(verbose_name="Start dato & tid")),
                (
                    "dateTo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Slut dato & tid"
                    ),
                ),
                (
                    "whoReserved",
                    models.TextField(max_length=140, verbose_name="Hvem er I?"),
                ),
                (
                    "where",
                    models.TextField(
                        default=None, max_length=140, null=True, verbose_name="Lokation"
                    ),
                ),
                (
                    "contactInfo",
                    models.CharField(max_length=140, verbose_name="Kontakt info"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Kommentarer")),
                (
                    "bartendersInCharge",
                    models.ManyToManyField(
                        to="bartenders.Bartender", verbose_name="Ansvarlige"
                    ),
                ),
            ],
            options={
                "verbose_name": "Udlejning af festtelt",
                "verbose_name_plural": "Udlejning af festtelt",
                "ordering": ("dateFrom",),
            },
        ),
    ]
