# Generated by Django 3.2.25 on 2025-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0005_udlejningtent"),
    ]

    operations = [
        migrations.AddField(
            model_name="udlejning",
            name="billSendTo",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Send regning til"
            ),
        ),
    ]
