# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0006_auto_20170325_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="udlejning",
            name="association",
            field=models.CharField(
                choices=[("internal", "Intern"), ("external", "Ekstern")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="udlejning",
            name="draftBeerSystem",
            field=models.CharField(
                choices=[("small", "Lille"), ("medium", "Mellem")],
                max_length=16,
                null=True,
            ),
        ),
    ]
