# Generated by Django 3.2.25 on 2025-07-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0006_udlejning_billsendto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="udlejning",
            options={
                "ordering": ("dateFrom",),
                "verbose_name": "Udlejning af fadølsanlæg",
                "verbose_name_plural": "Udlejning af fadølsanlæg",
            },
        ),
    ]
