# Generated by Django 3.2.25 on 2025-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0007_alter_udlejning_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udlejning",
            name="actualConsummation",
            field=models.TextField(blank=True, verbose_name="Faktisk forbrug"),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="comments",
            field=models.TextField(
                blank=True, max_length=1024, verbose_name="Kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="udlejning",
            name="expectedConsummation",
            field=models.TextField(
                help_text="Hvilke slags øl eller andre drikkevarer ønskes der og hvor mange fustager af hver type?",
                max_length=2048,
                verbose_name="Forventet forbrug",
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="comments",
            field=models.TextField(
                blank=True, max_length=1024, verbose_name="Kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="expectedConsummation",
            field=models.TextField(
                help_text="Hvilke slags øl eller andre drikkevarer ønskes der og hvor mange fustager af hver type?",
                max_length=2048,
                verbose_name="Forventet forbrug",
            ),
        ),
    ]
