# Generated by Django 6.0.4 on 2026-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0008_auto_20251207_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udlejning",
            name="draftBeerSystem",
            field=models.CharField(
                choices=[("small", "Lille anlæg"), ("barbaren", "BarBaren")],
                help_text="Hvilket anlæg vil I låne?",
                max_length=16,
                verbose_name="Fadølsanlæg",
            ),
        ),
    ]
