# Generated by Django 2.0.6 on 2018-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0008_auto_20180314_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdlejningApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField(verbose_name='Start dato')),
                ('dateTo', models.DateTimeField(blank=True, null=True, verbose_name='Slut dato')),
                ('whoReserved', models.CharField(max_length=140, verbose_name='Hvem er I?')),
                ('association', models.CharField(blank=True, choices=[('internal', 'Intern'), ('external', 'Ekstern')], max_length=16, verbose_name='Tilknytning')),
                ('draftBeerSystem', models.CharField(blank=True, choices=[('small', 'Lille'), ('medium', 'Mellem')], max_length=16, verbose_name='Fadølsanlæg')),
                ('whoPays', models.CharField(max_length=140, verbose_name='Hvem betaler?')),
                ('paymentType', models.CharField(max_length=140, verbose_name='Hvordan vil I betale?')),
                ('billSendTo', models.CharField(max_length=140)),
                ('where', models.TextField(max_length=140, verbose_name='Hvor skal det bruges?')),
                ('expectedConsummation', models.TextField(max_length=140, verbose_name='Forventet forbrug')),
                ('contactInfo', models.CharField(max_length=140, verbose_name='Kontaktinformation')),
                ('comments', models.TextField(blank=True, verbose_name='Kommentarer')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='association',
            field=models.CharField(blank=True, choices=[('internal', 'Intern'), ('external', 'Ekstern')], max_length=16, verbose_name='Tilknytning'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Kommentarer'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='contactInfo',
            field=models.CharField(max_length=140, verbose_name='Kontaktinformation'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='dateFrom',
            field=models.DateTimeField(verbose_name='Start dato'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='dateTo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Slut dato'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='draftBeerSystem',
            field=models.CharField(blank=True, choices=[('small', 'Lille'), ('medium', 'Mellem')], max_length=16, verbose_name='Fadølsanlæg'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='expectedConsummation',
            field=models.TextField(max_length=140, verbose_name='Forventet forbrug'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='paymentType',
            field=models.CharField(max_length=140, verbose_name='Hvordan vil I betale?'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='where',
            field=models.TextField(max_length=140, verbose_name='Hvor skal det bruges?'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='whoPays',
            field=models.CharField(max_length=140, verbose_name='Hvem betaler?'),
        ),
        migrations.AlterField(
            model_name='udlejning',
            name='whoReserved',
            field=models.CharField(max_length=140, verbose_name='Hvem er I?'),
        ),
    ]
