# Generated by Django 2.0.7 on 2018-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0011_auto_20180712_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udlejning",
            name="whoPays",
            field=models.CharField(
                help_text="Hvem skal regningen sendes til? (Fulde navn på person, virksomhed eller organisation)",
                max_length=140,
                verbose_name="Hvem betaler?",
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="whoPays",
            field=models.CharField(
                help_text="Hvem skal regningen sendes til? (Fulde navn på person, virksomhed eller organisation)",
                max_length=140,
                verbose_name="Hvem betaler?",
            ),
        ),
    ]
