# Generated by Django 2.0.7 on 2018-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0016_auto_20180714_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='udlejning',
            name='EANnumber',
            field=models.IntegerField(blank=True, help_text='Skal kun angives, hvis der skal faktureres til et EAN-nummer', null=True, verbose_name='EAN-nummer'),
        ),
        migrations.AddField(
            model_name='udlejningapplication',
            name='EANnumber',
            field=models.IntegerField(blank=True, help_text='Skal kun angives, hvis der skal faktureres til et EAN-nummer', null=True, verbose_name='EAN-nummer'),
        ),
    ]
