# Generated by Django 2.0.7 on 2018-07-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0018_auto_20180714_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="udlejning",
            name="status",
            field=models.CharField(
                choices=[
                    ("notsent", "Regning ikke sendt"),
                    ("sent", "Regning sendt"),
                    ("paid", "Regning betalt"),
                ],
                default="notsent",
                max_length=16,
            ),
        ),
    ]
