# Generated by Django 2.0.7 on 2018-07-15 03:18

from django.db import migrations


def paid_to_status(apps, schema_editor):
    Udlejning = apps.get_model('udlejning', 'Udlejning')
    for udlejning in Udlejning.objects.all():
        udlejning.status = 'paid' if udlejning.paid else 'notsent'
        udlejning.save()


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0019_udlejning_status'),
    ]

    operations = [
        migrations.RunPython(paid_to_status)
    ]
