# Generated by Django 2.0.7 on 2018-07-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0020_paid_to_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="udlejning", name="paid",),
    ]
