# Generated by Django 2.0.7 on 2018-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0021_remove_udlejning_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udlejning",
            name="EANnumber",
            field=models.BigIntegerField(
                blank=True,
                help_text="Skal kun angives, hvis der skal faktureres til et EAN-nummer",
                null=True,
                verbose_name="EAN-nummer",
            ),
        ),
        migrations.AlterField(
            model_name="udlejningapplication",
            name="EANnumber",
            field=models.BigIntegerField(
                blank=True,
                help_text="Skal kun angives, hvis der skal faktureres til et EAN-nummer",
                null=True,
                verbose_name="EAN-nummer",
            ),
        ),
    ]
