# Generated by Django 2.1.3 on 2018-12-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0024_auto_20181114_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udlejning",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Betalingsdato"),
        ),
    ]
