# Generated by Django 2.1.3 on 2018-12-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udlejning', '0025_auto_20181217_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udlejningapplication',
            name='draftBeerSystem',
        ),
    ]
