# Generated by Django 2.2.2 on 2019-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udlejning", "0026_remove_udlejningapplication_draftbeersystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="UdlejningProjector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateFrom", models.DateTimeField()),
                ("dateTo", models.DateTimeField()),
                ("whoReserved", models.TextField(blank=True, max_length=140)),
                ("contactInfo", models.CharField(blank=True, max_length=140)),
                ("comments", models.TextField(blank=True)),
            ],
            options={"ordering": ("dateFrom",),},
        ),
    ]
