version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
    groups:
      python-packages:
        patterns:
          - "*"
