#!/bin/bash
# No longer used by GitHub Actions, but can be used locally to build the image.
GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
name=ghcr.io/fredagscafeen/web
docker build -t "$name" -t "$name:$GIT_COMMIT_HASH" --build-arg "GIT_COMMIT_HASH=$GIT_COMMIT_HASH" .
