# Generated by Django 2.1.5 on 2019-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BT", "Til bartendere"),
                            ("BM", "Til bestyrelsesmedlemmer"),
                            ("ALL", "Til alle"),
                        ],
                        max_length=3,
                    ),
                ),
                ("document", models.FileField(upload_to="guides/")),
            ],
            options={"ordering": ("name",),},
        ),
    ]
