# Generated by Django 3.0.4 on 2020-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('ALL', 'Til alle'), ('BT', 'Til bartendere'), ('BM', 'Til bestyrelsesmedlemmer')], max_length=3),
        ),
    ]
