# Generated by Django 3.2.25 on 2025-11-02 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="updated_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Opdateret"
            ),
        ),
    ]
