# Generated by Django 3.2.25 on 2025-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_guide_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="language",
            field=models.CharField(
                choices=[("da", "Dansk"), ("en", "Engelsk")],
                default="da",
                max_length=2,
                verbose_name="Sprog",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="category",
            field=models.CharField(
                choices=[
                    ("ALL", "Til alle"),
                    ("BT", "Til bartendere"),
                    ("BM", "Til bestyrelsesmedlemmer"),
                ],
                max_length=3,
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="document",
            field=models.FileField(upload_to="guides/", verbose_name="Dokument"),
        ),
        migrations.AlterField(
            model_name="guide",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Name"),
        ),
    ]
