# Generated by Django 3.2.25 on 2025-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_auto_20251102_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="language",
            field=models.CharField(
                choices=[("da", "Danish"), ("en", "English")],
                default="da",
                max_length=2,
                verbose_name="Sprog",
            ),
        ),
    ]
