# Generated by Django 3.2.4 on 2024-11-04 11:17

import datetime

import django.core.validators
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models

import gallery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        null=True,
                        verbose_name="Udgivelsesdato",
                    ),
                ),
                (
                    "eventalbum",
                    models.BooleanField(default=True, verbose_name="Arrangement"),
                ),
                (
                    "gfyear",
                    models.PositiveSmallIntegerField(
                        default=gallery.utils.get_gfyear, verbose_name="Årgang"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Kort titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivelse"),
                ),
                ("oldFolder", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["gfyear", "-eventalbum", "oldFolder", "publish_date"],
                "unique_together": {("gfyear", "slug")},
            },
        ),
        migrations.CreateModel(
            name="BaseMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("I", "Image"),
                            ("V", "Video"),
                            ("A", "Audio"),
                            ("O", "Other"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Dato"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Synligt"),
                            ("discarded", "Frasorteret"),
                            ("sensitive", "Skjult"),
                            ("delete", "Slet"),
                            ("new", "Ubesluttet"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Synlighed",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Overskrift"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, null=True, verbose_name="Kort titel"),
                ),
                (
                    "forcedOrder",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-10000),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Rækkefølge",
                    ),
                ),
                (
                    "isCoverFile",
                    models.NullBooleanField(verbose_name="Vis på forsiden"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basemedia",
                        to="gallery.album",
                    ),
                ),
            ],
            options={
                "ordering": ["forcedOrder", "date", "slug"],
                "select_on_save": True,
                "unique_together": {("album", "slug")},
            },
        ),
        migrations.CreateModel(
            name="GenericFile",
            fields=[
                (
                    "basemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gallery.basemedia",
                    ),
                ),
                (
                    "originalFile",
                    models.FileField(blank=True, upload_to=gallery.utils.file_name),
                ),
                ("file", models.FileField(upload_to=gallery.utils.file_name)),
            ],
            options={
                "select_on_save": True,
            },
            bases=("gallery.basemedia",),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "basemedia_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gallery.basemedia",
                    ),
                ),
                (
                    "file",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to=gallery.utils.file_name
                    ),
                ),
            ],
            options={
                "select_on_save": True,
            },
            bases=("gallery.basemedia",),
        ),
    ]
