# Generated by Django 3.2.4 on 2024-11-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["year", "-eventalbum", "oldFolder", "publish_date"]},
        ),
        migrations.RenameField(
            model_name="album",
            old_name="gfyear",
            new_name="year",
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("year", "slug")},
        ),
    ]
