# Generated by Django 3.2.4 on 2024-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_auto_20241104_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="galleries"),
        ),
    ]
