# Generated by Django 3.2.4 on 2024-11-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_auto_20241104_1529"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["year", "-eventalbum", "oldFolder", "-publish_date"]},
        ),
    ]
