# Generated by Django 3.2.25 on 2024-12-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_album_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={
                "ordering": ["year", "bartenderalbum", "oldFolder", "-publish_date"]
            },
        ),
        migrations.RemoveField(
            model_name="album",
            name="eventalbum",
        ),
        migrations.AddField(
            model_name="album",
            name="bartenderalbum",
            field=models.BooleanField(
                default=False,
                help_text="Bartenderarrangementer er kun synlige for bartendere",
                verbose_name="Bartenderarrangement",
            ),
        ),
    ]
