# Generated by Django 3.2.25 on 2025-03-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_auto_20241230_2158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={
                "ordering": ["year", "bartenderalbum", "oldFolder", "-publish_date"],
                "verbose_name": "Album",
                "verbose_name_plural": "Albummer",
            },
        ),
    ]
