# Generated by Django 3.0.6 on 2020-10-06 13:45

from django.db import migrations, models

import email_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "token",
                    models.CharField(
                        default=email_auth.models.get_new_email_token, max_length=64
                    ),
                ),
            ],
        ),
    ]
