# Generated by Django 2.0.5 on 2018-05-22 11:20

import bartab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bartab', '0001_initial'), ('bartab', '0002_auto_20180522_1047'), ('bartab', '0003_auto_20180522_1057'), ('bartab', '0004_auto_20180522_1156'), ('bartab', '0005_auto_20180522_1251')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarTabEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BarTabSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarTabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hidden_from_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bartabentry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bartab.BarTabSnapshot'),
        ),
        migrations.AddField(
            model_name='bartabentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bartab.BarTabUser'),
        ),
        migrations.AddField(
            model_name='bartabentry',
            name='raw_added',
            field=bartab.models.SumField(blank=True),
        ),
        migrations.AddField(
            model_name='bartabentry',
            name='raw_used',
            field=bartab.models.SumField(blank=True),
        ),
        migrations.AlterField(
            model_name='bartabentry',
            name='added',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='bartabentry',
            name='used',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterUniqueTogether(
            name='bartabentry',
            unique_together={('user', 'snapshot')},
        ),
    ]
