# Generated by Django 3.0.6 on 2020-10-06 13:45

import bartab.sumfield
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bartenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarTabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hidden_from_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BarTabSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('bartender_shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bar_tab_snapshot', to='bartenders.BartenderShift')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('bartender_shift__start_datetime'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='BarTabEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_cash', models.NullBooleanField(verbose_name='Kontant?')),
                ('added', models.DecimalField(decimal_places=2, max_digits=11)),
                ('used', models.DecimalField(decimal_places=2, max_digits=11)),
                ('raw_added', bartab.sumfield.SumField(blank=True, verbose_name='Indsat')),
                ('raw_used', bartab.sumfield.SumField(blank=True, verbose_name='Køb')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bartab.BarTabSnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bartab.BarTabUser', verbose_name='Bruger')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('snapshot__bartender_shift__start_datetime'), descending=True, nulls_last=True),),
                'unique_together': {('user', 'snapshot')},
            },
        ),
    ]
