# Generated by Django 3.1.2 on 2020-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartabentry',
            name='added_cash',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontant?'),
        ),
    ]
