# Generated by Django 2.0.5 on 2018-05-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0001_squashed_0005_auto_20180522_1251"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartabentry", options={"ordering": ("snapshot__timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="bartabsnapshot", options={"ordering": ("timestamp",)},
        ),
    ]
