# Generated by Django 3.2.25 on 2026-04-04 13:32

from django.db import migrations
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    BarTabUser = apps.get_model("bartab", "BarTabUser")
    BarTabUser.objects.update(email=Lower("email"))


def reverse_lowercase(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0002_auto_20201020_1659"),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, reverse_lowercase),
    ]
