# Generated by Django 3.2.4 on 2024-07-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0002_auto_20201020_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartabentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indtastninger",
                to="bartab.bartabuser",
                verbose_name="Bruger",
            ),
        ),
    ]
