# Generated by Django 2.0.6 on 2018-06-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0002_auto_20180522_1651"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartabsnapshot", options={"ordering": ("-timestamp",)},
        ),
    ]
