# Generated by Django 6.0.4 on 2026-06-25 21:22

from django.db import migrations, models


def migrate_paymentmethod(apps, schema_editor):
    BarTabEntry = apps.get_model("bartab", "BarTabEntry")
    for entry in BarTabEntry.objects.all():
        if entry.added_cash:
            entry.payment_method = "cash"
        elif entry.added_cash == False:
            entry.payment_method = "card"
        else:
            entry.payment_method = "none"
        entry.save()


def reverse_migrate_paymentmethod(apps, schema_editor):
    pass  # No reverse migration needed, as the added_cash field is kept for backwards compatibility


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0003_lowercase_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartabentry",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=20,
                verbose_name="Betalingsmetode",
            ),
        ),
        migrations.RunPython(migrate_paymentmethod, reverse_migrate_paymentmethod),
    ]
