# Generated by Django 2.0.6 on 2018-07-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0025_auto_20180708_2326'),
        ('bartab', '0004_auto_20180708_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bartabentry',
            options={'ordering': ('snapshot__bartender_shift__start_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='bartabsnapshot',
            options={'ordering': ('-bartender_shift__start_datetime',)},
        ),
        migrations.AddField(
            model_name='bartabsnapshot',
            name='bartender_shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bar_tab_snapshot', to='bartenders.BartenderShift'),
        ),
    ]
