# Generated by Django 2.0.6 on 2018-07-08 22:29

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0007_auto_20180709_0029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartabentry",
            options={
                "ordering": (
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F(
                            "snapshot__bartender_shift__start_datetime"
                        ),
                        descending=True,
                        nulls_last=True,
                    ),
                )
            },
        ),
    ]
