# Generated by Django 2.0.8 on 2018-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0009_bartabentry_added_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartabentry',
            name='added_cash',
            field=models.NullBooleanField(verbose_name='Kontant?'),
        ),
    ]
