# Generated by Django 2.1.5 on 2019-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0011_auto_20180911_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
