# Generated by Django 2.1.5 on 2019-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0013_auto_20190211_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="name",
            field=models.CharField(
                choices=[
                    ("nygaard-394", "nygaard-394"),
                    ("studiecafeen", "studiecafeen"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
