# Generated by Django 2.2.2 on 2019-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0015_auto_20190211_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartabsnapshot',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
