# Generated by Django 2.2.2 on 2019-12-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0016_bartabsnapshot_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
