# Generated by Django 3.0.3 on 2020-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartab", "0017_delete_printer"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartabsnapshot",
            name="custom_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
