# Generated by Django 3.2.25 on 2025-04-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Skabelonavn")),
                (
                    "purpose",
                    models.TextField(max_length=255, verbose_name="Foreningens formål"),
                ),
                (
                    "representative",
                    models.CharField(max_length=255, verbose_name="Husrepræsentant"),
                ),
                (
                    "type",
                    models.CharField(max_length=255, verbose_name="Arrangementstype"),
                ),
                (
                    "guests",
                    models.CharField(
                        max_length=255, verbose_name="Forventet antal gæster"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oprettet den"
                    ),
                ),
                (
                    "key_figures",
                    models.ManyToManyField(
                        blank=True,
                        max_length=5,
                        related_name="key_figures",
                        to="bartenders.BoardMember",
                        verbose_name="Foreningens nøglepersoner",
                    ),
                ),
                (
                    "licensee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licensee",
                        to="bartenders.boardmember",
                        verbose_name="Bevillingshaver",
                    ),
                ),
                (
                    "loan_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_agreement",
                        to="bartenders.boardmember",
                        verbose_name="Låneaftale udfyldt af",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to="bartenders.boardmember",
                        verbose_name="Bestyrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logbogsskabelon",
                "verbose_name_plural": "Logbogsskabeloner",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Lokale")),
                (
                    "description",
                    models.TextField(
                        max_length=500, verbose_name="Afvigelser fra det normale"
                    ),
                ),
                (
                    "bartender_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bartenders.bartendershift",
                        verbose_name="Barvagt",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log.logbase",
                        verbose_name="Skabelon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logbog",
                "verbose_name_plural": "Logbøger",
                "ordering": ("-bartender_shift",),
            },
        ),
    ]
