# Generated by Django 3.2.25 on 2025-04-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbase",
            name="licensee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licensee",
                to="bartenders.bartender",
                verbose_name="Bevillingshaver",
            ),
        ),
    ]
