# Generated by Django 3.2.25 on 2025-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_alter_logbase_licensee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbase",
            name="name",
        ),
        migrations.AlterField(
            model_name="logentry",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Afvigelser fra det normale"
            ),
        ),
    ]
