# Generated by Django 3.2.25 on 2025-04-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
        ("log", "0003_auto_20250420_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="logbase",
            name="key_figures",
            field=models.ManyToManyField(
                blank=True,
                max_length=5,
                related_name="key_figures",
                to="bartenders.Bartender",
                verbose_name="Foreningens nøglepersoner",
            ),
        ),
        migrations.AlterField(
            model_name="logbase",
            name="loan_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_agreement",
                to="bartenders.bartender",
                verbose_name="Låneaftale udfyldt af",
            ),
        ),
        migrations.AlterField(
            model_name="logbase",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="bartenders.bartender",
                verbose_name="Bestyrer",
            ),
        ),
    ]
