# Generated by Django 3.2.25 on 2025-04-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0004_auto_20250420_1055"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntryContext",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
        migrations.AddField(
            model_name="logentry",
            name="au_personnel_contacted",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="AU-personale kontaktet og/eller tilkaldt",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="collective_evaluation",
            field=models.TextField(
                blank=True,
                max_length=400,
                verbose_name="Samlet vurdering af arrangementet",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="damages",
            field=models.TextField(blank=True, max_length=400, verbose_name="Skader"),
        ),
        migrations.AddField(
            model_name="logentry",
            name="fire_authority_contacted",
            field=models.BooleanField(
                default=False, verbose_name="Brandmyndigheder kontaktet"
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="medic_contacted",
            field=models.BooleanField(
                default=False, verbose_name="Ambulance/læge kontaktet"
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="police_contacted",
            field=models.BooleanField(default=False, verbose_name="Politi kontaktet"),
        ),
    ]
