# Generated by Django 3.2.25 on 2025-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0005_auto_20250421_2041"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntryContext",
        ),
    ]
