# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 09:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bartender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("username", models.CharField(max_length=140)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("studentNumber", models.IntegerField(blank=True, null=True)),
                ("phoneNumber", models.IntegerField(blank=True, null=True)),
                ("isActiveBartender", models.BooleanField(default=True)),
                ("isBoardMember", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("responsibilities", models.CharField(max_length=255)),
                (
                    "bartender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bartenders.Bartender",
                    ),
                ),
            ],
        ),
    ]
