# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0002_auto_20170325_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='BartenderApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('username', models.CharField(help_text='Brug evt. NFIT', max_length=140)),
                ('email', models.CharField(max_length=255)),
                ('studentNumber', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('info', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
