# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0002_auto_20170325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boardMembers'),
        ),
    ]
