# Generated by Django 3.2.4 on 2024-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0002_ballotlink_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=255,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=255,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
