# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-09 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0003_boardmember_image'),
        ('bartenders', '0003_bartenderapplication'),
    ]

    operations = [
    ]
