# Generated by Django 3.2.4 on 2024-10-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0003_auto_20240915_2045"),
        ("bartenders", "0003_auto_20241017_2029"),
    ]

    operations = []
