# Generated by Django 4.2 on 2024-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0003_auto_20240915_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="bartender",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("XXXL", "XXXL"),
                ],
                max_length=140,
                null=True,
                verbose_name="T-shirt størrelse",
            ),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("XXXL", "XXXL"),
                ],
                max_length=140,
                null=True,
                verbose_name="T-shirt størrelse",
            ),
        ),
    ]
