# Generated by Django 4.2 on 2024-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0003_auto_20240915_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="tshirt_size",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "XS"),
                    (1, "S"),
                    (2, "M"),
                    (3, "L"),
                    (4, "XL"),
                    (5, "XXL"),
                    (6, "XXXL"),
                ],
                null=True,
                verbose_name="T-shirt størrelse",
            ),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="tshirt_size",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "XS"),
                    (1, "S"),
                    (2, "M"),
                    (3, "L"),
                    (4, "XL"),
                    (5, "XXL"),
                    (6, "XXXL"),
                ],
                null=True,
                verbose_name="T-shirt størrelse",
            ),
        ),
    ]
