# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BartenderShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bartenders', models.ManyToManyField(related_name='Bartenders', to='bartenders.Bartender')),
                ('responsible', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bartenders.Bartender')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
