# Generated by Django 5.1.2 on 2024-10-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0004_alter_bartender_tshirt_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="En post.au mail fungerer ikke",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
