# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartender',
            name='isBoardMember',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='id',
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='bartender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bartenders.Bartender'),
        ),
    ]
