# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0005_bartendershift"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMemberDepositShift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("responsible", models.ManyToManyField(to="bartenders.Bartender")),
            ],
            options={"ordering": ("date",),},
        ),
    ]
