# Generated by Django 2.0.3 on 2018-03-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0005_auto_20180314_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
