# Generated by Django 3.2.4 on 2024-12-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0005_auto_20241212_2345"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmemberdepositshift",
            options={"ordering": ("-start_date",)},
        ),
    ]
