# Generated by Django 2.0.3 on 2018-03-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0006_boardmemberdepositshift"),
        ("bartenders", "0006_auto_20180314_2307"),
    ]

    operations = []
