# Generated by Django 3.2.4 on 2024-12-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0006_alter_boardmemberdepositshift_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartendershift",
            options={"ordering": ("start_datetime",)},
        ),
        migrations.AlterModelOptions(
            name="boardmemberdepositshift",
            options={"ordering": ("start_date",)},
        ),
    ]
