# Generated by Django 2.0.3 on 2018-03-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0007_merge_20180317_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartendershift",
            name="bartenders",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"isActiveBartender": True},
                related_name="Bartenders",
                to="bartenders.Bartender",
            ),
        ),
        migrations.AlterField(
            model_name="bartendershift",
            name="responsible",
            field=models.ForeignKey(
                limit_choices_to={"boardmember__isnull": False},
                on_delete=django.db.models.deletion.PROTECT,
                to="bartenders.Bartender",
            ),
        ),
        migrations.AlterField(
            model_name="boardmemberdepositshift",
            name="responsible",
            field=models.ManyToManyField(
                limit_choices_to={"boardmember__isnull": False},
                to="bartenders.Bartender",
            ),
        ),
    ]
