# Generated by Django 3.2.25 on 2025-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0007_auto_20241214_0030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={"ordering": ("period", "bartender")},
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="responsibilities",
            field=models.CharField(
                help_text="F.eks. Formand, Kasserer, Suppleant eller andet",
                max_length=255,
                verbose_name="Ansvarsområde",
            ),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titel"),
        ),
    ]
