# Generated by Django 3.2.25 on 2025-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0008_auto_20250315_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="responsibilities",
            field=models.CharField(
                help_text="(Hvis mere end et ansvarsområde, separer med ' / ')",
                max_length=255,
                verbose_name="Ansvarsområde",
            ),
        ),
    ]
