# Generated by Django 2.0.3 on 2018-03-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0008_auto_20180317_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartendershift',
            name='bartenders',
            field=models.ManyToManyField(blank=True, limit_choices_to={'isActiveBartender': True}, related_name='shifts', to='bartenders.Bartender'),
        ),
        migrations.AlterField(
            model_name='boardmemberdepositshift',
            name='responsible',
            field=models.ManyToManyField(limit_choices_to={'boardmember__isnull': False}, related_name='deposit_shifts', to='bartenders.Bartender'),
        ),
    ]
