# Generated by Django 3.2.25 on 2025-07-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0009_alter_boardmember_responsibilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleasedBartenderShift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bartender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="released_bartender_shift",
                        to="bartenders.bartender",
                    ),
                ),
                (
                    "bartender_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="released_bartender_shift",
                        to="bartenders.bartendershift",
                    ),
                ),
            ],
            options={
                "unique_together": {("bartender_shift", "bartender")},
            },
        ),
    ]
