# Generated by Django 2.0.3 on 2018-03-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0010_auto_20180317_2112"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardmemberdepositshift",
            old_name="responsible",
            new_name="responsibles",
        ),
    ]
