# Generated by Django 3.2.25 on 2025-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0010_releasedbartendershift"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartender",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("orange", "Orange"),
                ],
                max_length=10,
                null=True,
                verbose_name="Color",
            ),
        ),
    ]
