# Generated by Django 3.2.25 on 2025-08-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0011_bartender_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bartender",
            name="prefer_only_early_shifts",
        ),
    ]
