# Generated by Django 2.0.3 on 2018-03-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0011_auto_20180317_2112"),
    ]

    operations = [
        migrations.AlterField("BartenderShift", "date", models.DateTimeField())
    ]
