# Generated by Django 3.2.25 on 2025-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0012_remove_bartender_prefer_only_early_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartender",
            name="isOnTheMailingLists",
            field=models.BooleanField(default=False),
        ),
    ]
