# Generated by Django 3.2.25 on 2025-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0012_remove_bartender_prefer_only_early_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartendershift",
            name="info",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Additional information about the shift",
            ),
        ),
    ]
