# Generated by Django 3.2.25 on 2025-08-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0013_bartender_isonthemailinglists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bartender",
            name="isOnTheMailingLists",
        ),
    ]
