# Generated by Django 2.0.3 on 2018-03-18 21:20

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0013_auto_20180318_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartendershift',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
