# Generated by Django 3.2.25 on 2025-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0013_bartendershift_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartendershift",
            name="info_url",
            field=models.URLField(
                blank=True, verbose_name="Link to additional information"
            ),
        ),
        migrations.AddField(
            model_name="bartendershift",
            name="info_url_is_external",
            field=models.BooleanField(
                default=False, verbose_name="Is the link to an external site?"
            ),
        ),
    ]
