# Generated by Django 3.2.25 on 2025-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0014_auto_20250912_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("gold", "Gold"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("orange", "Orange"),
                ],
                max_length=10,
                null=True,
                verbose_name="Color",
            ),
        ),
    ]
