# Generated by Django 2.0.3 on 2018-03-18 21:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0014_bartendershift_end_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartendershift", options={"ordering": ("start_datetime",)},
        ),
        migrations.AlterModelOptions(
            name="boardmemberdepositshift", options={"ordering": ("start_date",)},
        ),
        migrations.RenameField(
            model_name="bartendershift",
            old_name="start_date",
            new_name="start_datetime",
        ),
        migrations.RenameField(
            model_name="boardmemberdepositshift",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="boardmemberdepositshift",
            name="end_date",
            field=models.DateField(default=datetime.datetime(2, 2, 2, 0, 0)),
            preserve_default=False,
        ),
    ]
