# Generated by Django 2.0.3 on 2018-03-18 22:14

from django.db import migrations, models

import bartenders.models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0015_auto_20180318_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartendershift",
            name="start_datetime",
            field=models.DateTimeField(
                default=bartenders.models.next_bartender_shift_start
            ),
        ),
        migrations.AlterField(
            model_name="boardmemberdepositshift",
            name="end_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="boardmemberdepositshift",
            name="start_date",
            field=models.DateField(default=bartenders.models.next_deposit_shift_start),
        ),
    ]
