# Generated by Django 3.2.25 on 2025-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0015_alter_bartender_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmember",
            name="alias",
            field=models.CharField(default="best", max_length=50, verbose_name="Alias"),
        ),
    ]
