# Generated by Django 2.0.3 on 2018-03-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0016_auto_20180318_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='username',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
