# Generated by Django 3.2.25 on 2025-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0016_boardmember_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartender",
            name="birthday",
            field=models.DateField(
                help_text="DD.MM.YYYY", null=True, verbose_name="Fødselsdato"
            ),
        ),
        migrations.AddField(
            model_name="bartender",
            name="prefered_language",
            field=models.CharField(
                choices=[("da", "Danish"), ("en", "English")],
                default="da",
                max_length=2,
                null=True,
                verbose_name="Preferred language",
            ),
        ),
        migrations.AddField(
            model_name="bartenderapplication",
            name="birthday",
            field=models.DateField(
                help_text="DD.MM.YYYY", null=True, verbose_name="Fødselsdato"
            ),
        ),
        migrations.AddField(
            model_name="bartenderapplication",
            name="prefered_language",
            field=models.CharField(
                choices=[("da", "Danish"), ("en", "English")],
                default="da",
                max_length=2,
                null=True,
                verbose_name="Preferred language",
            ),
        ),
    ]
