# Generated by Django 2.0.3 on 2018-03-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0017_auto_20180319_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartendershift',
            name='other_bartenders',
            field=models.ManyToManyField(blank=True, related_name='shifts', to='bartenders.Bartender'),
        ),
        migrations.AlterField(
            model_name='bartendershift',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bartenders.Bartender'),
        ),
        migrations.AlterField(
            model_name='boardmemberdepositshift',
            name='responsibles',
            field=models.ManyToManyField(related_name='deposit_shifts', to='bartenders.Bartender'),
        ),
    ]
