# Generated by Django 3.2.25 on 2026-02-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0018_auto_20251219_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bartendershift",
            name="info",
        ),
        migrations.RemoveField(
            model_name="bartendershift",
            name="info_url",
        ),
        migrations.RemoveField(
            model_name="bartendershift",
            name="info_url_is_external",
        ),
    ]
