# Generated by Django 2.0.3 on 2018-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0019_auto_20180326_2044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartenderapplication",
            name="username",
            field=models.CharField(max_length=140, verbose_name="Brugernavn"),
        ),
    ]
