# Generated by Django 3.2.25 on 2026-04-04 13:29

from django.db import migrations
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    BartenderUser = apps.get_model("bartenders", "Bartender")
    BartenderUser.objects.update(email=Lower("email"))


def reverse_lowercase(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0019_auto_20260224_2005"),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, reverse_lowercase),
    ]
