# Generated by Django 2.0.4 on 2018-04-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0020_auto_20180331_1936"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember", options={"ordering": ("title",)},
        ),
    ]
