# Generated by Django 2.0.5 on 2018-05-12 21:12

import bartenders.models
from django.db import migrations, models
from django.utils.crypto import get_random_string


EMAIL_TOKEN_LENGTH = 64
def get_new_email_token():
    return get_random_string(EMAIL_TOKEN_LENGTH)


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0022_auto_20180512_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartender',
            name='email_token',
            field=models.CharField(default=get_new_email_token, editable=False, max_length=64),
        ),
    ]
