# Generated by Django 2.0.5 on 2018-05-12 21:12

import bartenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartenders', '0022_auto_20180512_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartender',
            name='email_token',
            field=models.CharField(default=bartenders.models.new_email_token, editable=False, max_length=64),
        ),
    ]
