# Generated by Django 2.0.6 on 2018-07-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0026_auto_20180710_0021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="email",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="bartenderapplication",
            name="email",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
