# Generated by Django 2.1.5 on 2019-01-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0027_auto_20180710_0031"),
    ]

    operations = [
        migrations.RemoveField(model_name="bartender", name="email_token",),
    ]
