# Generated by Django 2.1.5 on 2019-01-28 20:20

import django.db.models.deletion
from django.db import migrations, models


def set_boardmember_id(apps, schema_editor):
    BoardMember = apps.get_model("bartenders", "BoardMember")
    for b in BoardMember.objects.all():
        b._id = b.pk
        b.save()


def reverse_set_boardmember_id(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0028_remove_bartender_email_token"),
    ]

    operations = [
        # Create new field for new primary key
        # We can't call it "id" yet
        migrations.AddField(
            model_name="boardmember",
            name="_id",
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        # Copy current primary key (bartender) value to _id
        migrations.RunPython(set_boardmember_id, reverse_set_boardmember_id),
        # Remove bartender as the primary key, resulting in there being no primary key at all
        migrations.AlterField(
            model_name="boardmember",
            name="bartender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bartenders.Bartender"
            ),
        ),
        # Change _id to be like an implicit django primary key field
        migrations.AlterField(
            model_name="boardmember",
            name="_id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        # Rename _id to id
        migrations.RenameField(
            model_name="boardmember", old_name="_id", new_name="id",
        ),
    ]
