# Generated by Django 2.1.5 on 2019-01-28 20:31

import datetime

import django.db.models.deletion
from django.db import migrations, models


def set_boardmember_period(apps, schema_editor):
    CURRENT_PERIOD_START = datetime.date(2018, 3, 2)

    BoardMemberPeriod = apps.get_model("bartenders", "BoardMemberPeriod")
    period = BoardMemberPeriod.objects.create(start_date=CURRENT_PERIOD_START)

    BoardMember = apps.get_model("bartenders", "BoardMember")
    for b in BoardMember.objects.all():
        b.period = period
        b.save()


def reverse_set_boardmember_period(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0029_change_boardmember_primary_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMemberPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="boardmember",
            name="period",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bartenders.BoardMemberPeriod",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_boardmember_period, reverse_set_boardmember_period),
        migrations.AlterField(
            model_name="boardmember",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bartenders.BoardMemberPeriod",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardmember", unique_together={("bartender", "period")},
        ),
    ]
