# Generated by Django 2.1.5 on 2019-01-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0031_auto_20190129_0025"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember", options={"ordering": ("period", "title")},
        ),
    ]
