# Generated by Django 2.2 on 2019-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0032_auto_20190129_0040"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartender",
            name="prefer_only_early_shifts",
            field=models.BooleanField(default=False),
        ),
    ]
