# Generated by Django 2.2 on 2019-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0033_bartender_prefer_only_early_shifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bartender",
            name="prefer_only_early_shifts",
            field=models.BooleanField(
                default=False,
                verbose_name="Jeg foretrækker ikke at have nogle sene barvagter",
            ),
        ),
    ]
