# Generated by Django 2.2.2 on 2019-07-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0036_auto_20190703_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="bartender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_members",
                to="bartenders.Bartender",
            ),
        ),
    ]
