# Generated by Django 2.2.4 on 2019-08-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0037_auto_20190709_2137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bartendershiftperiod",
            options={"ordering": ("-generation_datetime",)},
        ),
    ]
