# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Breweries',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=140, null=True)),
                ('priceInDKK', models.FloatField(default=0.0)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('container', models.CharField(blank=True, choices=[('DRAFT', 'Fad'), ('BOTTLE', 'Flaske'), ('SHOT', 'Shot'), ('FOOD', 'Madvare'), ('OTHER', 'Andet')], max_length=140, null=True)),
                ('volumeInCentiliters', models.IntegerField(blank=True, null=True)),
                ('inStock', models.BooleanField(default=False)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Brewery')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.BeerType')),
            ],
        ),
    ]
