# Generated by Django 3.2.4 on 2024-07-27 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BeerType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("name_dk", models.CharField(blank=True, max_length=140, null=True)),
                ("description", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Brewery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("website", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Breweries",
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("name_dk", models.CharField(blank=True, max_length=140, null=True)),
                ("description", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=140)),
                ("priceInDKK", models.DecimalField(decimal_places=0, max_digits=11)),
                ("abv", models.FloatField(blank=True, null=True)),
                ("container", models.CharField(blank=True, max_length=140, null=True)),
                (
                    "container_dk",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
                ("volumeInCentiliters", models.IntegerField(blank=True, null=True)),
                ("inStock", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items")),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("lastModified", models.DateTimeField(auto_now=True, null=True)),
                ("link", models.CharField(blank=True, max_length=255)),
                (
                    "brewery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="items.brewery",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="items.beertype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="items.item",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="items.inventorysnapshot",
                    ),
                ),
            ],
        ),
    ]
