# Generated by Django 3.2.4 on 2024-07-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="beertype",
            name="name_dk",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="container_dk",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items"),
        ),
        migrations.AddField(
            model_name="item",
            name="name_dk",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="container",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
