# Generated by Django 3.2.25 on 2025-10-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="glutenFree",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="nonAlcoholic",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ShelfItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_items",
                        to="items.item",
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_items",
                        to="items.shelf",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "item__name"),
                "unique_together": {("shelf", "item")},
            },
        ),
    ]
