# Generated by Django 3.2.25 on 2026-02-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_auto_20260131_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="priceInDKK",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
