# Generated by Django 3.2.25 on 2026-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_priceindkk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="container",
            field=models.CharField(default="", max_length=140),
        ),
    ]
