# Generated by Django 3.2.25 on 2026-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_item_container"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="container",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
