# Generated by Django 3.2.25 on 2026-02-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_item_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="bestBefore",
            field=models.DateField(blank=True, null=True, verbose_name="Best before"),
        ),
        migrations.AlterField(
            model_name="item",
            name="abv",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Alcohol by volume"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="container",
            field=models.CharField(
                blank=True,
                help_text="E.g., 'Bottle', 'Can', 'Keg'",
                max_length=140,
                null=True,
                verbose_name="Container",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="country",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Country of origin"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="item",
            name="glutenFree",
            field=models.BooleanField(default=False, verbose_name="Gluten free"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="items", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="inStock",
            field=models.BooleanField(default=True, verbose_name="In stock"),
        ),
        migrations.AlterField(
            model_name="item",
            name="link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=140, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="nonAlcoholic",
            field=models.BooleanField(default=False, verbose_name="Non-alcoholic"),
        ),
        migrations.AlterField(
            model_name="item",
            name="priceInDKK",
            field=models.DecimalField(
                decimal_places=2, max_digits=11, verbose_name="Price (DKK)"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="volumeInCentiliters",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Volume in centiliters"
            ),
        ),
    ]
