# Generated by Django 2.1.7 on 2019-03-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_auto_20181016_0245"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ("name",)},),
    ]
