# Generated by Django 3.2.25 on 2026-04-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_auto_20260224_1554"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Fridge",
                "verbose_name_plural": "Fridges",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="beertype",
            options={
                "ordering": ("name",),
                "verbose_name": "Beer type",
                "verbose_name_plural": "Beer types",
            },
        ),
        migrations.AlterModelOptions(
            name="brewery",
            options={
                "ordering": ("name",),
                "verbose_name": "Brewery",
                "verbose_name_plural": "Breweries",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.AlterModelOptions(
            name="shelf",
            options={
                "ordering": ("name",),
                "verbose_name": "Shelf",
                "verbose_name_plural": "Shelves",
            },
        ),
        migrations.AlterModelOptions(
            name="shelfitem",
            options={
                "ordering": ("order", "item__name"),
                "verbose_name": "Shelf item",
                "verbose_name_plural": "Shelf items",
            },
        ),
        migrations.AlterField(
            model_name="beertype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="beertype",
            name="link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="beertype",
            name="name",
            field=models.CharField(max_length=140, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="name",
            field=models.CharField(max_length=140, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="brewery",
            name="website",
            field=models.CharField(blank=True, max_length=255, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="name",
            field=models.CharField(max_length=140, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="shelf",
            name="fridge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shelves",
                to="items.fridge",
            ),
        ),
    ]
