# Generated by Django 3.2.25 on 2026-03-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_auto_20260328_2302"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hideOnShelf",
            field=models.BooleanField(default=False, verbose_name="Hide on shelf"),
        ),
    ]
