# Generated by Django 6.0.4 on 2026-06-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_auto_20260402_2330"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fridge",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Fridge",
                "verbose_name_plural": "Fridges",
            },
        ),
        migrations.AlterModelOptions(
            name="shelfitem",
            options={
                "ordering": ("order", "shelf", "item"),
                "verbose_name": "Shelf item",
                "verbose_name_plural": "Shelf items",
            },
        ),
        migrations.RemoveField(
            model_name="shelf",
            name="fridge",
        ),
        migrations.AddField(
            model_name="fridge",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="abv",
            field=models.FloatField(
                blank=True,
                help_text="E.g., 5.0 for 5% ABV",
                null=True,
                verbose_name="Alcohol by volume",
            ),
        ),
        migrations.AlterField(
            model_name="shelfitem",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.CreateModel(
            name="FridgeShelfAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Order"
                    ),
                ),
                (
                    "fridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_assignments",
                        to="items.fridge",
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fridge_assignments",
                        to="items.shelf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fridge Shelf",
                "verbose_name_plural": "Fridge Shelves",
                "ordering": ("order", "fridge", "shelf"),
                "unique_together": {("fridge", "shelf")},
            },
        ),
    ]
