# Generated by Django 6.0.4 on 2026-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_fridge_options_alter_shelfitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="isBeerOfTheMonth",
            field=models.BooleanField(
                default=False, verbose_name="Is beer of the month"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="isOnSpotlight",
            field=models.BooleanField(
                default=False, verbose_name="Is on this week's spotlight"
            ),
        ),
    ]
