# Generated by Django 2.2.2 on 2019-11-26 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_inventoryentry_inventorysnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysnapshot',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
