services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    environment:
      - DJANGO_SETTINGS_MODULE=fredagscafeen.settings.devcontainer
    command: sleep infinity
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
