# Generated by Django 6.0.4 on 2026-08-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bartenders", "0020_lowercase_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutOfPocketExpense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_registration_number",
                    models.CharField(
                        help_text="The registration number of the bank account. i.e. the first four digits of the account number.",
                        max_length=4,
                        verbose_name="Bank Registration Number",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        help_text="The account number without the registration number.",
                        max_length=10,
                        verbose_name="Bank Account Number",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense has been paid out.",
                        verbose_name="Completed",
                    ),
                ),
                (
                    "bartender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_of_pocket_expenses",
                        to="bartenders.bartender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Out of Pocket Expense",
                "verbose_name_plural": "Out of Pocket Expenses",
                "permissions": [
                    (
                        "complete_expenses",
                        "Can mark out of pocket expenses as completed",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutOfPocketExpenseItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount in DKK.",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accountant.outofpocketexpense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Out of Pocket Expense Item",
                "verbose_name_plural": "Out of Pocket Expense Items",
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("s3_object_key", models.CharField(max_length=1024)),
                (
                    "expense_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="accountant.outofpocketexpenseitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Attachment",
                "verbose_name_plural": "Expense Attachments",
            },
        ),
    ]
