# Generated by Django 6.0.4 on 2026-08-31 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outofpocketexpenseitem",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="The date the expense was made.",
                verbose_name="Date",
            ),
        ),
    ]
