# Generated by Django 3.2.25 on 2025-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bartenders", "0012_remove_bartender_prefer_only_early_shifts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Navn"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="mailing_lists",
                        to="bartenders.Bartender",
                        verbose_name="Medlemmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailingliste",
                "verbose_name_plural": "Mailinglister",
                "ordering": ["name"],
            },
        ),
    ]
