# Generated by Django 3.2.25 on 2025-08-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Navn"),
                ),
                (
                    "numOfMembers",
                    models.IntegerField(default=0, verbose_name="Antal medlemmer"),
                ),
            ],
        ),
    ]
