# Generated by Django 3.2.25 on 2025-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartenders", "0013_bartender_isonthemailinglists"),
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="members",
            field=models.ManyToManyField(
                related_name="mailing_lists",
                to="bartenders.Bartender",
                verbose_name="Medlemmer",
            ),
        ),
    ]
