# Generated by Django 3.2.25 on 2025-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="isOnlyInternal",
            field=models.BooleanField(
                default=False,
                verbose_name="Only list members can send to this mailing list",
            ),
        ),
    ]
