# Generated by Django 3.2.25 on 2025-08-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mailinglist_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "ordering": ["name"],
                "verbose_name": "Mailingliste",
                "verbose_name_plural": "Mailinglister",
            },
        ),
        migrations.RemoveField(
            model_name="mailinglist",
            name="numOfMembers",
        ),
    ]
