# Generated by Django 3.2.25 on 2025-11-19 16:45

import django.db.models.deletion
from django.db import migrations, models

import mail.fields
import mail.validators


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mailinglist_isonlyinternal"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=254,
                        validators=[mail.validators.validate_template_syntax],
                        verbose_name="Subject",
                    ),
                ),
                (
                    "email_html_text",
                    models.TextField(
                        blank=True,
                        validators=[mail.validators.validate_template_syntax],
                        verbose_name="Email HTML text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
        ),
        migrations.CreateModel(
            name="OutgoingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to",
                    mail.fields.CommaSeparatedEmailField(verbose_name="Til email(s)"),
                ),
                (
                    "cc",
                    mail.fields.CommaSeparatedEmailField(blank=True, verbose_name="Cc"),
                ),
                (
                    "bcc",
                    mail.fields.CommaSeparatedEmailField(
                        blank=True, verbose_name="Bcc"
                    ),
                ),
                (
                    "reply_to",
                    mail.fields.CommaSeparatedEmailField(
                        blank=True, verbose_name="Svar til"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=100, verbose_name="Emne"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Besked")),
                (
                    "html_message",
                    models.TextField(
                        blank=True,
                        help_text="Used only if template is not selected",
                        verbose_name="HTML besked",
                    ),
                ),
                (
                    "from_mailing_list",
                    models.ForeignKey(
                        help_text="@fredagscafeen.dk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_email",
                        to="mail.mailinglist",
                        verbose_name="Fra mailingliste",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="If template is selected, HTML message and subject fields will not be used - they will be populated from template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail.emailtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Udgående mail",
                "verbose_name_plural": "Udgående mails",
            },
        ),
        migrations.CreateModel(
            name="TemplateVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=254, verbose_name="Variable name"),
                ),
                ("value", models.TextField(blank=True, verbose_name="Variable value")),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail.outgoingemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template variable",
                "verbose_name_plural": "Template variables",
            },
        ),
    ]
