# Generated by Django 3.2.25 on 2025-11-19 20:19

from django.db import migrations, models

import mail.models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_emailtemplate_outgoingemail_templatevariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=mail.models.get_attachment_save_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The original filename",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                ("mimetype", models.CharField(blank=True, default="", max_length=255)),
                (
                    "emails",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attachments",
                        to="mail.OutgoingEmail",
                        verbose_name="Emails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
    ]
