# Generated by Django 3.2.25 on 2026-04-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_uuid', models.UUIDField(unique=True)),
                ('s3_object_key', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('sender', models.CharField(max_length=320)),
                ('target', models.CharField(max_length=320)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('DROPPED', 'Dropped')], max_length=9)),
                ('reason', models.TextField(blank=True)),
                ('mail_archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mail', to='mail.mailarchive')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_mails', to='mail.mailinglist')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=320)),
                ('forwarded_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('FORWARDED', 'Forwarded'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], max_length=9)),
                ('reason', models.TextField(blank=True)),
                ('incoming_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_attempts', to='mail.incomingmail')),
                ('previous_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='mail.forwardedmail')),
            ],
        ),
    ]
