# Generated by Django 3.2.25 on 2026-04-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_forwardedmail_previous_attempt_integrity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forwardedmail",
            name="previous_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retry_attempts",
                to="mail.forwardedmail",
            ),
        ),
    ]
