# Generated by Django 3.2.25 on 2026-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_alter_forwardedmail_previous_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamFilterTLD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tld",
                    models.CharField(
                        help_text="Domain to filter on, supports everything after @ in an email address (e.g. 'example.com' or '.com' to filter all .com domains)",
                        max_length=255,
                        unique=True,
                        verbose_name="TLD",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for the TLD, help the next person understand the purpose of this entry",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "allowed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether emails from this TLD should be allowed or blocked",
                        verbose_name="Allowed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spam filter TLD",
                "verbose_name_plural": "Spam filter TLDs",
            },
        ),
    ]
