# Generated by Django 3.2.25 on 2026-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0008_spamfiltertld"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingmail",
            name="subject",
            field=models.CharField(blank=True, max_length=384),
        ),
    ]
