# Generated by Django 6.0.4 on 2026-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_traefik", "Can view Traefik Dashboard"),
                    ("view_garage", "Can view Garage S3 WebUI"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
