# Generated by Django 6.0.4 on 2026-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for the QR code. If left blank, it will be generated from the name. <br><strong>Live Link:</strong> <code class='loading-placeholder'>Generating preview...</code> <br><em>Note: Once printed, the slug should not be changed, as the physical QR code relies on it.</em>",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for the QR code.", max_length=255
                    ),
                ),
                (
                    "destination",
                    models.URLField(
                        help_text="The URL that the QR code will redirect to when scanned. This should be a valid URL.",
                        max_length=2000,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the QR code is active and can be scanned.",
                    ),
                ),
                (
                    "scan_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="The number of times the QR code has been scanned.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dynamic QR-code",
                "verbose_name_plural": "Dynamic QR-codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
