# Generated by Django 3.2.25 on 2026-04-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikeys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="granularapikey",
            name="prefix",
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
    ]
